server:
  port: 8691

db:
  host: localhost
  schema: purchase
  username: tech_challenge
  password: 102030
  port: 3366

aws:
  resources:
    sqs:
      cart-closed.queue: local-purchase-cart-closed-queue
      payment-done.queue: local-purchase-payment-done-queue
      payment-created.queue: local-payment-created-queue
    sns:
      purchase-created.topic: local-purchase-created-topic
      purchase-paid.topic: local-purchase-paid-topic
      purchase-notification.topic: local-purchase-status-notification-topic

spring:
  cloud:
    aws:
      endpoint: http://localhost:4566
      region:
        static: us-east-1
