db:
  host: #defined at task definition
  schema: #defined at task definition
  username: #defined at task definition
  password: #defined at task definition
  port: 3306

aws:
  resources:
    sqs:
      cart-closed.queue: prd-purchase-cart-closed-queue
      payment-done.queue: prd-purchase-payment-done-queue
      payment-created.queue: prd-purchase-payment-created-queue
    sns:
      purchase-created.topic: prd-purchase-created-topic
      purchase-paid.topic: prd-purchase-paid-topic
      purchase-notification.topic: prd-purchase-status-notification-topic

spring:
  cloud:
    aws:
      region:
        static: us-east-1
