name: Create Tag Release

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    name: Create New Tag Release
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          fetch-depth: 0
          fetch-tags: true

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Build Project
        env:
          GITHUB_TOKEN: ${{ secrets.JAVA_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew build -x test

      - name: Create Release Tag
        id: tag_release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          ./gradlew release \
            -Prelease.forceSnapshot \
            -Prelease.customUsername=${{ github.actor }} \
            -Prelease.customPassword=${{ github.token }}